### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by jostyee** [icymind/SmartIM#1]
I tried this plugin, but seems doesn't solve the problem, for example:

- I want to enter the insert mode of vintage, so I click `i` while at Chinese input mode, it still popups candidates words instead of switch mode.
- Switch input method to English manually, clicking `i` then the plugin notifies it changes successfully, which is already English.
- Then click `Esc` keeps to English after entering normal mode.

So it acts the same as w/o the plugin installed, I wonder what the right behavior of it to be used.

Thanks in advance.

**Comment by jostyee** [comment]
seems this plugin has permission issue on 10.13 High Sierra:

```log
Traceback (most recent call last):
  File "/Users/yee/Library/Application Support/Sublime Text 3/Packages/SmartIM/SmartIM.py", line 27, in <lambda>
    view.settings().add_on_change('command_mode', lambda: self.callback(view))
  File "/Users/yee/Library/Application Support/Sublime Text 3/Packages/SmartIM/SmartIM.py", line 61, in callback
    self.IMEs[id] = subprocess.check_output([self.BINPATH]).decode('utf-8').strip()
  File "./python3.3/subprocess.py", line 576, in check_output
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1448, in _execute_child
PermissionError: [Errno 13] Permission denied
```

**Comment by lanx-x** [comment]
thanks for your feedback.
smartIM lost its execute permission in High Sierra, you can temporarily fix it by:
`chmod +x  ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/SmartIM/im-select`

**Comment by jostyee** [comment]
@icymind Thanks, the permission issue has been fixed now.
But I'm sorry I still don't get the plugin's usage, can you please be kind to give a simple explanation, please?

**Comment by lanx-x** [comment]
- when you leave insert mode, your current input method will be save, then smartIM switch to english keyboard layout automatically. 
- when you enter insert mode again, smartIM will restore the input method saved before.

**Comment by jostyee** [comment]
oic, I was confused 'cause I test it when switching back from other apps, thanks again, it's really helpful.
